[variables]
NIXPACKS_NO_GENERATE_DOCKERFILE = "1"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cp -r backend/* . && npm ci --only=production"]

[phases.build]
cmds = ["echo 'Backend setup complete'"]

[start]
cmd = "node server.js"